version: 2

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - revive
    - gocritic
  disable:
    - depguard

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: if-return
        disabled: true
  gosec:
    excludes:
      - G402 # Insecure TLS config (we knowingly allow InsecureSkipVerify via provider option)
  gocritic:
    disabled-checks:
      - ifElseChain

output:
  formats:
    - format: colored-line-number