linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - gosec
    - unconvert
    - goconst
    - goimports
    - copyloopvar
    - gofumpt

linters-settings:
  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    autofix: true
    local-prefixes: github.com/ClickHouse/terraform-provider-clickhousedbops

run:
  timeout: 10m
  skip-dirs:
  skip-dirs-default: true
