version: 2

run:
  timeout: 5m
  tests: true

issues:
  exclude-use-default: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - revive
    - gocritic
  disable:
    - depguard

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: if-return
        disabled: true
  gosec:
    excludes:
      - G402
  gocritic:
    disabled-checks:
      - ifElseChain

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true