version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - unused
    - revive
    - gocritic
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-results: true