version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  sort-order:
    - linter
    - file
